# Generated by Django 3.1.2 on 2021-01-26 21:01

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210123_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactusDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('csubject', models.CharField(max_length=100)),
                ('cphonenumber', models.CharField(max_length=15)),
                ('cemail', models.EmailField(max_length=20)),
                ('cmsg', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'ContactUStable',
            },
            managers=[
                ('contactdbobject', django.db.models.manager.Manager()),
            ],
        ),
    ]
