# Generated by Django 3.1.2 on 2021-02-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contactusdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='ufirstname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='users',
            name='ulastname',
        ),
    ]
