# Generated by Django 3.1.2 on 2021-03-30 18:15

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210222_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausername', models.CharField(max_length=50)),
                ('apassword', models.CharField(max_length=10)),
                ('amail', models.EmailField(max_length=15)),
                ('aphone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'admin_user',
            },
            managers=[
                ('adminobject', django.db.models.manager.Manager()),
            ],
        ),
    ]
