# Generated by Django 3.1.2 on 2021-03-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_adminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='amail',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactusdb',
            name='cemail',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='umail',
            field=models.EmailField(max_length=50),
        ),
    ]
