# Generated by Django 3.1.2 on 2021-05-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210406_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminuser',
            old_name='amail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='adminuser',
            old_name='apassword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='adminuser',
            old_name='aphone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='adminuser',
            old_name='ausername',
            new_name='username',
        ),
    ]
