# Generated by Django 3.1.2 on 2021-05-18 09:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210514_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_respinse',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_Email', models.EmailField(max_length=30)),
                ('image_path', models.CharField(max_length=50)),
                ('prediction_made', models.CharField(max_length=100)),
                ('user_response', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'user_result_response',
            },
            managers=[
                ('userresponse_model_obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
