# Generated by Django 3.1.2 on 2021-05-18 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_respinse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_respinse',
            new_name='user_response',
        ),
    ]
