# Generated by Django 3.1.2 on 2021-05-18 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210518_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_response',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
